# Generated by Django 3.1.7 on 2021-03-28 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CipherProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_of_product', models.CharField(max_length=30, verbose_name='Шифр изделия')),
                ('description_cipher_of_product', models.CharField(max_length=150, verbose_name='Расшифровка')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=30, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='FormatDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_format', models.CharField(max_length=30, verbose_name='Шифр формата')),
            ],
        ),
        migrations.CreateModel(
            name='PrefixDecimalNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_prefix', models.CharField(max_length=20, verbose_name='Шифр приставки')),
                ('note_prefix_of_decimal_number', models.CharField(max_length=100, verbose_name='Примечание')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOfDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status_document', models.CharField(max_length=50, verbose_name='Название статуса документа')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_status_file', models.CharField(max_length=50, verbose_name='Название статуса файла')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_of_type_file', models.CharField(max_length=50, verbose_name='Шифр типа файла')),
                ('description_of_type_file', models.CharField(max_length=150, verbose_name='Описание')),
                ('extension_file', models.CharField(max_length=50, verbose_name='Расширение файла')),
            ],
        ),
        migrations.CreateModel(
            name='TypeDesignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipher_of_type_document', models.CharField(max_length=50, verbose_name='Шифр типа документа')),
                ('name_of_type_document', models.CharField(max_length=150, verbose_name='Наименование документа')),
                ('id_type_file_porter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.typeoffile')),
            ],
        ),
        migrations.CreateModel(
            name='DesignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal_number', models.CharField(max_length=30, verbose_name='Децимальный номер')),
                ('name_dd', models.CharField(max_length=100, verbose_name='Название')),
                ('date_create', models.DateField(verbose_name='Дата создания')),
                ('amount_sheet_dd', models.IntegerField(verbose_name='Количество листов')),
                ('note_dd', models.CharField(max_length=150, verbose_name='Примечание')),
                ('inventory_number_dd', models.IntegerField(verbose_name='Инвентарный номер')),
                ('id_cipher_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.cipherproduct')),
                ('id_format_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.formatdocument')),
                ('id_prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.prefixdecimalnumber')),
                ('id_status_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.statusofdocument')),
                ('id_type_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.typedesigndocument')),
            ],
        ),
    ]
