# Generated by Django 3.1.7 on 2021-03-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixdecimalnumber',
            name='note_prefix_of_decimal_number',
            field=models.CharField(default=None, max_length=100, verbose_name='Примечание'),
        ),
    ]
