# Generated by Django 3.1.7 on 2021-03-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0002_auto_20210328_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prefixdecimalnumber',
            name='note_prefix_of_decimal_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Примечание'),
        ),
    ]
