# Generated by Django 3.1.7 on 2021-03-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0003_auto_20210328_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cipherproduct',
            options={'verbose_name': 'Шифр изделия', 'verbose_name_plural': 'Шифры изделия'},
        ),
        migrations.AlterModelOptions(
            name='departmentcompany',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='designdocument',
            options={'verbose_name': 'Конструкторская документация', 'verbose_name_plural': 'Конструкторская документация'},
        ),
        migrations.AlterModelOptions(
            name='formatdocument',
            options={'verbose_name': 'Формат документа', 'verbose_name_plural': 'Форматы документа'},
        ),
        migrations.AlterModelOptions(
            name='prefixdecimalnumber',
            options={'verbose_name': 'Код организации', 'verbose_name_plural': 'Коды организации'},
        ),
        migrations.AlterModelOptions(
            name='statusofdocument',
            options={'verbose_name': 'Статус документа', 'verbose_name_plural': 'Статусы документа'},
        ),
        migrations.AlterModelOptions(
            name='statusoffile',
            options={'verbose_name': 'Статус файла документа', 'verbose_name_plural': 'Статусы файла документа'},
        ),
        migrations.AlterModelOptions(
            name='typedesigndocument',
            options={'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документа'},
        ),
        migrations.AlterModelOptions(
            name='typeoffile',
            options={'verbose_name': 'Шифр файла документа', 'verbose_name_plural': 'Шифры файла документа'},
        ),
        migrations.RenameField(
            model_name='designdocument',
            old_name='id_prefix',
            new_name='Код организации',
        ),
        migrations.RenameField(
            model_name='designdocument',
            old_name='id_status_document',
            new_name='Статус документа',
        ),
        migrations.RenameField(
            model_name='designdocument',
            old_name='id_format_document',
            new_name='Формат документа',
        ),
        migrations.RenameField(
            model_name='designdocument',
            old_name='id_type_document',
            new_name='Шифр документа',
        ),
        migrations.RenameField(
            model_name='designdocument',
            old_name='id_cipher_product',
            new_name='Шифр изделия',
        ),
        migrations.RemoveField(
            model_name='typedesigndocument',
            name='id_type_file_porter',
        ),
        migrations.RemoveField(
            model_name='typeoffile',
            name='extension_file',
        ),
        migrations.AlterField(
            model_name='cipherproduct',
            name='cipher_of_product',
            field=models.CharField(max_length=30, unique=True, verbose_name='Шифр изделия'),
        ),
        migrations.AlterField(
            model_name='departmentcompany',
            name='name_department',
            field=models.CharField(max_length=30, unique=True, verbose_name='Название отдела'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='decimal_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='Децимальный номер'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='inventory_number_dd',
            field=models.IntegerField(unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='note_dd',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='formatdocument',
            name='name_format',
            field=models.CharField(max_length=30, unique=True, verbose_name='Шифр формата'),
        ),
        migrations.AlterField(
            model_name='prefixdecimalnumber',
            name='name_of_prefix',
            field=models.CharField(max_length=20, unique=True, verbose_name='Код организации'),
        ),
        migrations.AlterField(
            model_name='prefixdecimalnumber',
            name='note_prefix_of_decimal_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='statusofdocument',
            name='name_status_document',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название статуса документа'),
        ),
        migrations.AlterField(
            model_name='statusoffile',
            name='name_status_file',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название статуса файла'),
        ),
        migrations.AlterField(
            model_name='typedesigndocument',
            name='cipher_of_type_document',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Шифр документа'),
        ),
        migrations.AlterField(
            model_name='typedesigndocument',
            name='name_of_type_document',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование документа'),
        ),
        migrations.AlterField(
            model_name='typeoffile',
            name='cipher_of_type_file',
            field=models.CharField(max_length=50, unique=True, verbose_name='Шифр типа файла'),
        ),
        migrations.AlterField(
            model_name='typeoffile',
            name='description_of_type_file',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание'),
        ),
    ]
