# Generated by Django 3.1.7 on 2021-04-01 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0005_auto_20210330_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='designdocument',
            old_name='Код организации',
            new_name='id_prefix',
        ),
    ]
