# Generated by Django 3.1.7 on 2021-04-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0006_auto_20210401_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designdocument',
            name='id_prefix',
        ),
        migrations.RemoveField(
            model_name='designdocument',
            name='Статус документа',
        ),
        migrations.RemoveField(
            model_name='designdocument',
            name='Тип документа',
        ),
        migrations.RemoveField(
            model_name='designdocument',
            name='Формат документа',
        ),
        migrations.RemoveField(
            model_name='designdocument',
            name='Шифр изделия',
        ),
    ]
