# Generated by Django 3.1.7 on 2021-04-01 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0007_auto_20210401_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdocument',
            name='id_cipher_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_document.cipherproduct', verbose_name='Шифр изделия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designdocument',
            name='id_format_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_document.formatdocument', verbose_name='Формат документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designdocument',
            name='id_prefix',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_document.prefixdecimalnumber', verbose_name='Код организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designdocument',
            name='id_status_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_document.statusofdocument', verbose_name='Статус документа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designdocument',
            name='id_type_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_document.typedesigndocument', verbose_name='Тип документа'),
            preserve_default=False,
        ),
    ]
