# Generated by Django 3.1.7 on 2021-04-01 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0010_auto_20210401_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDesignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_od_document', models.FileField(upload_to='')),
                ('file_od_document_2', models.FilePathField(match='test.pdf', path='D:/django')),
                ('id_design_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.designdocument', verbose_name='Децимальный номер')),
                ('id_type_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.typeoffile', verbose_name='Тип файла документа')),
            ],
        ),
    ]
