# Generated by Django 3.1.7 on 2021-04-01 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0011_filedesigndocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedesigndocument',
            name='file_od_document_2',
        ),
    ]
