# Generated by Django 3.1.7 on 2021-04-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0012_remove_filedesigndocument_file_od_document_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedesigndocument',
            name='file_od_document',
        ),
        migrations.AddField(
            model_name='filedesigndocument',
            name='okey.pdf',
            field=models.FileField(default=1, upload_to='test/'),
            preserve_default=False,
        ),
    ]
