# Generated by Django 3.1.7 on 2021-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0013_auto_20210401_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedesigndocument',
            name='okey.pdf',
        ),
        migrations.AddField(
            model_name='filedesigndocument',
            name='file_od_document',
            field=models.FileField(default=1, upload_to='test/', verbose_name='okey.pdf'),
            preserve_default=False,
        ),
    ]
