# Generated by Django 3.1.7 on 2021-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0014_auto_20210401_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='filedesigndocument',
            name='version_of_dd',
            field=models.PositiveIntegerField(default='1', editable=False, verbose_name='версия докумена'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='amount_sheet_dd',
            field=models.PositiveIntegerField(verbose_name='Количество листов'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='inventory_number_dd',
            field=models.PositiveIntegerField(unique=True, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='filedesigndocument',
            name='file_od_document',
            field=models.FileField(upload_to='test/'),
        ),
    ]
