# Generated by Django 3.1.7 on 2021-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0015_auto_20210403_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedesigndocument',
            options={'verbose_name': 'Файл документа', 'verbose_name_plural': 'Файлы документов'},
        ),
        migrations.RemoveField(
            model_name='filedesigndocument',
            name='version_of_dd',
        ),
        migrations.AddField(
            model_name='designdocument',
            name='version_of_dd',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Версия докумена'),
        ),
    ]
