# Generated by Django 3.1.7 on 2021-04-03 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0016_auto_20210403_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filedesigndocument',
            options={'verbose_name': 'Файл документа', 'verbose_name_plural': 'Файлы документа'},
        ),
        migrations.RemoveField(
            model_name='designdocument',
            name='version_of_dd',
        ),
        migrations.RemoveField(
            model_name='filedesigndocument',
            name='id_design_document',
        ),
        migrations.CreateModel(
            name='CorrectionDesignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(verbose_name='Дата введения')),
                ('note_dd', models.CharField(blank=True, max_length=150, null=True, verbose_name='Примечание')),
                ('version_of_dd', models.PositiveIntegerField(default=0, editable=False, verbose_name='Порядковый номер коррекции')),
                ('id_design_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design_document.designdocument', verbose_name='Децимальный номер')),
            ],
            options={
                'verbose_name': 'Коррекция КД',
                'verbose_name_plural': 'Коррекции КД',
            },
        ),
        migrations.AddField(
            model_name='filedesigndocument',
            name='id_correction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='design_document.correctiondesigndocument', verbose_name='Децимальный номер'),
            preserve_default=False,
        ),
    ]
