# Generated by Django 3.1.7 on 2021-04-04 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_document', '0017_auto_20210403_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatdocument',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='decimal_number',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\d{1}\\.\\d{3}\\.\\d{3})(\\-\\d{2})?$')], verbose_name='Децимальный номер'),
        ),
    ]
