# Generated by Django 3.1.7 on 2021-04-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0018_auto_20210404_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formatdocument',
            name='author',
        ),
    ]
