# Generated by Django 3.1.7 on 2021-04-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0019_remove_formatdocument_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusOfFile',
        ),
        migrations.RemoveField(
            model_name='filedesigndocument',
            name='file_od_document',
        ),
        migrations.AddField(
            model_name='filedesigndocument',
            name='file_of_document',
            field=models.FileField(default=1, upload_to='file_of_dd/', verbose_name='Загрузите файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typedesigndocument',
            name='description_of_type_document',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание документа'),
        ),
    ]
