# Generated by Django 3.1.7 on 2021-04-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0020_auto_20210411_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typedesigndocument',
            name='cipher_of_type_document',
            field=models.CharField(default='', max_length=50, verbose_name='Шифр документа'),
        ),
    ]
