# Generated by Django 3.1.7 on 2021-04-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0022_auto_20210413_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusofdocument',
            name='color_status_document',
            field=models.CharField(default='', max_length=50, verbose_name='Цвет надписи'),
        ),
        migrations.AlterField(
            model_name='filedesigndocument',
            name='file_of_document',
            field=models.FileField(upload_to='design_document/static/design_document/file_of_dd', verbose_name='Загрузите файл'),
        ),
    ]
