# Generated by Django 3.1.7 on 2021-04-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0023_auto_20210416_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusofdocument',
            name='color_status_document',
            field=models.CharField(max_length=50, unique=True, verbose_name='Цвет надписи'),
        ),
    ]
