# Generated by Django 3.1.7 on 2021-04-22 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_document', '0024_auto_20210418_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdocument',
            name='id_user_work_with_doc',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Сотрудник'),
            preserve_default=False,
        ),
    ]
