# Generated by Django 3.1.7 on 2021-04-22 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_document', '0025_designdocument_id_user_work_with_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='id_user_work_with_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='inventory_number_dd',
            field=models.PositiveIntegerField(verbose_name='Инвентарный номер'),
        ),
    ]
