# Generated by Django 3.1.7 on 2021-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0026_auto_20210422_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoffile',
            name='extension_file',
            field=models.CharField(default=1, max_length=20, verbose_name='Разширение файла'),
            preserve_default=False,
        ),
    ]
