# Generated by Django 3.1.7 on 2021-04-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0027_typeoffile_extension_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentCompany',
        ),
        migrations.AlterModelOptions(
            name='typeoffile',
            options={'verbose_name': 'Тип файла документа', 'verbose_name_plural': 'Типы файла документа'},
        ),
    ]
