# Generated by Django 3.1.7 on 2021-04-25 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design_document', '0028_auto_20210423_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiondesigndocument',
            name='id_design_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.designdocument', verbose_name='Децимальный номер'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='id_cipher_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.cipherproduct', verbose_name='Шифр изделия'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='id_format_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.formatdocument', verbose_name='Формат документа'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='id_prefix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.prefixdecimalnumber', verbose_name='Код организации'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='id_status_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.statusofdocument', verbose_name='Статус документа'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='id_type_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.typedesigndocument', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='designdocument',
            name='id_user_work_with_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='filedesigndocument',
            name='id_correction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.correctiondesigndocument', verbose_name='Децимальный номер'),
        ),
        migrations.AlterField(
            model_name='filedesigndocument',
            name='id_type_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='design_document.typeoffile', verbose_name='Тип файла документа'),
        ),
    ]
