# Generated by Django 3.1.7 on 2021-05-10 11:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0029_auto_20210425_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='decimal_number',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(regex='^(\\d{1}\\.\\d{3}\\.\\d{3})(\\-\\d{2})?$')], verbose_name='Децимальный номер'),
        ),
    ]
