# Generated by Django 3.1.7 on 2021-07-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0030_auto_20210510_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdocument',
            name='Подтвердить изменения',
            field=models.BooleanField(default=False),
        ),
    ]
