# Generated by Django 3.1.7 on 2021-07-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0031_designdocument_подтвердить изменения'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='Подтвердить изменения',
            field=models.NullBooleanField(default=False),
        ),
    ]
