# Generated by Django 3.1.7 on 2021-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0032_auto_20210718_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='Подтвердить изменения',
            field=models.BooleanField(default=False),
        ),
    ]
