# Generated by Django 3.1.7 on 2021-07-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0035_auto_20210718_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designdocument',
            name='Подтвердить изменения',
        ),
        migrations.AddField(
            model_name='designdocument',
            name='confirm_change',
            field=models.BooleanField(default=False, verbose_name='Подтвердить изменения'),
        ),
    ]
