# Generated by Django 3.2 on 2021-07-19 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0038_auto_20210718_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='inventory_number_dd',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(regex='^(\\d+)(\\-\\d+)?$')], verbose_name='Инвентарный номер'),
        ),
    ]
