# Generated by Django 2.2.12 on 2021-09-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design_document', '0039_alter_designdocument_inventory_number_dd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cipherproduct',
            options={'ordering': ['cipher_of_product'], 'verbose_name': 'Шифр изделия', 'verbose_name_plural': 'Шифры изделия'},
        ),
        migrations.AlterModelOptions(
            name='correctiondesigndocument',
            options={'ordering': ['id_design_document'], 'verbose_name': 'Коррекция КД', 'verbose_name_plural': 'Коррекции КД'},
        ),
        migrations.AlterModelOptions(
            name='designdocument',
            options={'ordering': ['id_prefix', 'decimal_number'], 'verbose_name': 'Конструкторская документация', 'verbose_name_plural': 'Конструкторская документация'},
        ),
        migrations.AlterModelOptions(
            name='filedesigndocument',
            options={'ordering': ['id_correction', 'id_type_file'], 'verbose_name': 'Файл документа', 'verbose_name_plural': 'Файлы документа'},
        ),
        migrations.AlterModelOptions(
            name='formatdocument',
            options={'ordering': ['name_format'], 'verbose_name': 'Формат документа', 'verbose_name_plural': 'Форматы документа'},
        ),
        migrations.AlterModelOptions(
            name='prefixdecimalnumber',
            options={'ordering': ['name_of_prefix'], 'verbose_name': 'Код организации', 'verbose_name_plural': 'Коды организации'},
        ),
        migrations.AlterModelOptions(
            name='statusofdocument',
            options={'ordering': ['name_status_document'], 'verbose_name': 'Статус документа', 'verbose_name_plural': 'Статусы документа'},
        ),
        migrations.AlterModelOptions(
            name='typedesigndocument',
            options={'ordering': ['numb_order', 'cipher_of_type_document'], 'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документа'},
        ),
        migrations.AlterModelOptions(
            name='typeoffile',
            options={'ordering': ['cipher_of_type_file'], 'verbose_name': 'Тип файла документа', 'verbose_name_plural': 'Типы файла документа'},
        ),
        migrations.AddField(
            model_name='typedesigndocument',
            name='numb_order',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='typedesigndocument',
            name='cipher_of_type_document',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Шифр документа'),
        ),
    ]
